### ISSUE TITLE
macOS Development Exec fails on binding

### ISSUE THREAD

**Issue by miguemely** [Impostor/Impostor#128]
# Bug Report

## Base Information
Operating System = Darwin Miguels-iMac.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

Imposter Version = Impostor-Server_1.2.2-ci.97_osx-x64

DotNet Version = dotnet-runtime-5.0.0-rc.2.20475.5-osx-x64

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms 
```
miguelr@Miguels-iMac Impostor-Server_1.2.2-ci.97_osx-x64 % ./Impostor.Server       
[23:57:14 INF] Starting Impostor
[23:57:14 FTL] Impostor terminated unexpectedly
System.Net.Sockets.SocketException (45): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_DontFragment(Boolean value)
   at System.Net.Sockets.UdpClient.set_DontFragment(Boolean value)
   at Impostor.Hazel.Udp.UdpConnectionListener..ctor(IPEndPoint endPoint, ObjectPool`1 readerPool, IPMode ipMode)
   at Impostor.Server.Net.Matchmaker.StartAsync(IPEndPoint ipEndPoint)
   at Impostor.Server.Net.MatchmakerService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Impostor.Server.Program.Main(String[] args)
```

## Reproduction
Run development server artifact.

**Comment by miguemely** [comment]
Artifacts in question:
https://ci.appveyor.com/project/Impostor/Impostor/builds/36191196/artifacts

**Comment by reecebenson** [comment]
I was able to also replicate this.

SDK Version: 5.0.100-rc.2.20479.15
Impostor: [Impostor-Server_1.2.2-ci.97_osx-x64](https://ci.appveyor.com/project/Impostor/Impostor/builds/36191196/artifacts) (and also [Impostor-Server_1.2.2-ci.95_osx-x64](https://ci.appveyor.com/project/Impostor/Impostor/builds/36147569/artifacts))
OS:
- System Version: macOS 10.15.7 (19H2)
- Kernel Version: Darwin 19.6.0

```bash
➜  testing wget https://ci.appveyor.com/api/buildjobs/dh5ukadylutcwmjb/artifacts/build%2FImpostor-Server_1.2.2-ci.97_osx-x64.tar.gz
[snip]
HTTP request sent, awaiting response... 200 OK
Length: 1285026 (1.2M) [application/octet-stream]
Saving to: ‘build%2FImpostor-Server_1.2.2-ci.97_osx-x64.tar.gz’

build%2FImpostor-Se 100%[===================>]   1.22M   969KB/s    in 1.3s    

2020-11-10 09:49:50 (969 KB/s) - ‘build%2FImpostor-Server_1.2.2-ci.97_osx-x64.tar.gz’ saved [1285026/1285026]

➜  testing $ tar xvzf build%2FImpostor-Server_1.2.2-ci.97_osx-x64.tar.gz 
x config.json
x Impostor.Api.pdb
x Impostor.Hazel.pdb
x Impostor.Server
x Impostor.Server.pdb

➜  testing $ ./Impostor.Server
[09:50:48 INF] Starting Impostor
[09:50:51 FTL] Impostor terminated unexpectedly
System.Net.Sockets.SocketException (45): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_DontFragment(Boolean value)
   at System.Net.Sockets.UdpClient.set_DontFragment(Boolean value)
   at Impostor.Hazel.Udp.UdpConnectionListener..ctor(IPEndPoint endPoint, ObjectPool`1 readerPool, IPMode ipMode)
   at Impostor.Server.Net.Matchmaker.StartAsync(IPEndPoint ipEndPoint)
   at Impostor.Server.Net.MatchmakerService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Impostor.Server.Program.Main(String[] args)
```

**Comment by reecebenson** [comment]
This fails on `Impostor.Hazel/Udp/UdpConnectionListener.cs`, when setting the `DontFragment` variable.

Changing:
```csharp
_socket = new UdpClient(endPoint)
{
    DontFragment = true
};
```

To:
```csharp
_socket = new UdpClient(endPoint);
```

Resolves this issue, but I haven't tested for adverse effects (and haven't tested the connection.)

**Comment by miguemely** [comment]
This does not seem to be fixed.

on CI build 110:

`miguelr@Miguels-iMac Impostor-Server_1.2.2-ci.110_osx-x64 % ./Impostor.Server
[16:10:10 INF] Starting Impostor v1.2.2-ci.110
[16:10:10 FTL] Impostor terminated unexpectedly
System.Net.Sockets.SocketException (45): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_DontFragment(Boolean value)
   at System.Net.Sockets.UdpClient.set_DontFragment(Boolean value)
   at Impostor.Hazel.Udp.UdpConnectionListener..ctor(IPEndPoint endPoint, ObjectPool`1 readerPool, IPMode ipMode)
   at Impostor.Server.Net.Matchmaker.StartAsync(IPEndPoint ipEndPoint)
   at Impostor.Server.Net.MatchmakerService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Impostor.Server.Program.Main(String[] args)
miguelr@Miguels-iMac Impostor-Server_1.2.2-ci.110_osx-x64 % `
