### ISSUE TITLE
running file gives this error

### ISSUE THREAD

**Issue by epicwappy20** [Impostor/Impostor#304]
running home compiled from vs gives this

[18:23:37 INF] Starting Impostor v1.0.0
[18:23:38 DBG] Hosting starting
[18:23:38 FTL] Impostor terminated unexpectedly
System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.UdpClient..ctor(IPEndPoint localEP)
   at Impostor.Hazel.Udp.UdpConnectionListener..ctor(IPEndPoint endPoint, ObjectPool`1 readerPool, IPMode ipMode) in C:\Users\me\Documents\GitHub\Impostor\src\Impostor.Hazel\Udp\UdpConnectionListener.cs:line 51
   at Impostor.Server.Net.Matchmaker.StartAsync(IPEndPoint ipEndPoint) in C:\Users\me\Documents\GitHub\Impostor\src\Impostor.Server\Net\Matchmaker.cs:line 43
   at Impostor.Server.Net.MatchmakerService.StartAsync(CancellationToken cancellationToken) in C:\Users\(me)\Documents\GitHub\Impostor\src\Impostor.Server\Net\MatchmakerService.cs:line 34
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Impostor.Server.Program.Main(String[] args) in C:\Users\me\Documents\GitHub\Impostor\src\Impostor.Server\Program.cs:line 62

C:\Users\me\Documents\GitHub\Impostor\src\Impostor.Server\bin\Debug\net5.0\Impostor.Server.exe (process 25488) exited with code 1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by dimaguy** [comment]
The port being requested is already in use, either free up the one impostor is asking for 22023, or choose another one.
You most likely didnt close correctly the previous instance correctly, so try rebooting.
