### ISSUE TITLE
Client unexpected disconnected from server caused by Invoking data received failed

### ISSUE THREAD

**Issue by lightsing** [Impostor/Impostor#475]
# Bug Report

## Base Information
- Windows 11 for Amoung US
- `Linux 5.4.0-108-generic #122-Ubuntu` and `Docker version 20.10.14, build a224086` for Impostor
- Impostor Version: docker aeonlucid/impostor:nightly a05a4187f49a
- Among Us Version:  v2022.3.29s (build num: 1864)

### Mod Used
- https://github.com/yukinogatari/TheOtherRoles-GM v3.5.5.1
- https://github.com/OhMyGuus/BetterCrewLink

### Server Configuration
```json
{
  "Server": {
    "PublicIp": "**REDACTED**",
    "ListenIp": "0.0.0.0"
  },
  "AntiCheat": {
    "Enabled": false
  }
}
```

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Client unexpected disconnected from server caused by Invoking data received failed.

### Server log
```
impostor    | [14:34:08 WRN] Client **REDACTED** (114) was caught cheating: [61] Client sent unregistered call
impostor    | [14:34:08 ERR] Invoking data received failed
impostor    | System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
impostor    |    at Impostor.Hazel.MessageReader.ReadUInt16() in /source/src/Impostor.Hazel/Hazel/MessageReader.cs:line 154
impostor    |    at Impostor.Hazel.MessageReader.ReadMessage() in /source/src/Impostor.Hazel/Hazel/MessageReader.cs:line 66
impostor    |    at Impostor.Server.Net.State.Game.HandleGameDataAsync(IMessageReader parent, ClientPlayer sender, Boolean toPlayer) in /source/src/Impostor.Server/Net/State/Game.Data.cs:line 81
impostor    |    at Impostor.Server.Net.Client.HandleMessageAsync(IMessageReader reader, MessageType messageType) in /source/src/Impostor.Server/Net/Client.cs:line 298
impostor    |    at Impostor.Server.Net.Hazel.HazelConnection.ConnectionOnDataReceived(DataReceivedEventArgs e) in /source/src/Impostor.Server/Net/Hazel/HazelConnection.cs:line 71
impostor    |    at Impostor.Hazel.Connection.InvokeDataReceived(MessageReader msg, MessageType messageType) in /source/src/Impostor.Hazel/Hazel/Connection.cs:line 193
impostor    | [14:34:08 INF] DDBINW - Player **REDACTED** (114) has left.
impostor    | [14:34:08 INF] DDBINW - Assigned **REDACTED** (124) as new host. 
impostor    | [14:34:08 INF] Client 114 disconnecting, reason: Invoking data received failed 
```
```
impostor    | [14:34:08 WRN] Client **REDACTED** (124) was caught cheating: [SetSkin] Client sent unregistered call
impostor    | [14:34:08 WRN] Client **REDACTED** (124) was caught cheating: [SetVisor] Client sent unregistered call
impostor    | [14:34:08 WRN] Client **REDACTED** (124) was caught cheating: [SetNamePlate] Client sent unregistered call
impostor    | [14:34:08 WRN] Client **REDACTED** (124) was caught cheating: [SetLevel] Client sent unregistered call
impostor    | [14:34:11 ERR] Invoking data received failed
impostor    | System.NotImplementedException: The method or operation is not implemented.
impostor    |    at Impostor.Server.Net.Inner.Objects.Components.InnerPlayerPhysics.DeserializeAsync(IClientPlayer sender, IClientPlayer target, IMessageReader reader, Boolean initialState) in /source/src/Impostor.Server/Net/Inner/Objects/Components/InnerPlayerPhysics.cs:line 35
impostor    |    at Impostor.Server.Net.State.Game.HandleGameDataAsync(IMessageReader parent, ClientPlayer sender, Boolean toPlayer) in /source/src/Impostor.Server/Net/State/Game.Data.cs:line 90
impostor    |    at Impostor.Server.Net.Client.HandleMessageAsync(IMessageReader reader, MessageType messageType) in /source/src/Impostor.Server/Net/Client.cs:line 298
impostor    |    at Impostor.Server.Net.Hazel.HazelConnection.ConnectionOnDataReceived(DataReceivedEventArgs e) in /source/src/Impostor.Server/Net/Hazel/HazelConnection.cs:line 71
impostor    |    at Impostor.Hazel.Connection.InvokeDataReceived(MessageReader msg, MessageType messageType) in /source/src/Impostor.Hazel/Hazel/Connection.cs:line 193
impostor    | [14:34:11 INF] DDBINW - Player **REDACTED** (124) has left.
impostor    | [14:34:11 INF] DDBINW - Assigned **REDACTED** (127) as new host.
impostor    | [14:34:11 INF] Client 124 disconnecting, reason: Invoking data received failed
```

```
impostor    | [14:34:11 WRN] Client **REDACTED** (127) was caught cheating: [SetLevel] Client sent unregistered call
impostor    | [14:34:14 ERR] Invoking data received failed
impostor    | System.NotImplementedException: The method or operation is not implemented.
impostor    |    at Impostor.Server.Net.Inner.Objects.Components.InnerPlayerPhysics.DeserializeAsync(IClientPlayer sender, IClientPlayer target, IMessageReader reader, Boolean initialState) in /source/src/Impostor.Server/Net/Inner/Objects/Components/InnerPlayerPhysics.cs:line 35
impostor    |    at Impostor.Server.Net.State.Game.HandleGameDataAsync(IMessageReader parent, ClientPlayer sender, Boolean toPlayer) in /source/src/Impostor.Server/Net/State/Game.Data.cs:line 90
impostor    |    at Impostor.Server.Net.Client.HandleMessageAsync(IMessageReader reader, MessageType messageType) in /source/src/Impostor.Server/Net/Client.cs:line 298
impostor    |    at Impostor.Server.Net.Hazel.HazelConnection.ConnectionOnDataReceived(DataReceivedEventArgs e) in /source/src/Impostor.Server/Net/Hazel/HazelConnection.cs:line 71
impostor    |    at Impostor.Hazel.Connection.InvokeDataReceived(MessageReader msg, MessageType messageType) in /source/src/Impostor.Hazel/Hazel/Connection.cs:line 193
impostor    | [14:34:14 INF] DDBINW - Player **REDACTED** (127) has left.
impostor    | [14:34:14 INF] DDBINW - Assigned **REDACTED** (129) as new host.
```

## Reproduction

Just play with these mods?

**Comment by miniduikboot** [comment]
Hi there, can you explain what you or another player in your game did that caused these exceptions? Did a player just activate a special ability from one of the roles? It would really help to know which ability activation is causing this issue

**Comment by lightsing** [comment]
sorry for that, i checked the footage and i cannot find anything special.

**Comment by NikoCat233** [comment]
I just meet that today, when the host leaves and a new host is being selected, the anticheat seems want to kick everyone and everyone disconnects with InvokeDataReceived

**Comment by miniduikboot** [comment]
Can you share more details, like which anticheat message was being triggered?

**Comment by NikoCat233** [comment]
Sorry but I deleted the log

**Comment by miniduikboot** [comment]
Then I can't take action on this issue.
